### PR TITLE
fix(formula): case sensitive

### LINKED ISSUE #1472: [Bug] VLOOKUP公式计算不出结果
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、单元格=VLOOKUP("john",A1:E4,1,0)
image

### 预期行为

计算出结果
image

### 实际行为

计算不出结果报#n/a
image

### 运行环境

_No response_

### 系统信息

_No response_

### PR DESCRIPTION
**Pull request by Dushusir**
close #1472

## Pull Request Checklist

- [x] Related tickets or issues have been linked in the PR description (or missing issue).
- [x] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [x] Unit tests have been added for the changes (if applicable).
- [x] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by DR-Univer — APPROVED** [review]

File: packages/engine-formula/src/engine/utils/object-compare.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export function findCompareToken(str: string): [compareToken, BaseValueObject] {
  * 2. >=apple*: normal value, >apple: obtains the same effect as >=apple*
  * 3. <apple*: normal value, <=apple: obtains the same effect as <apple*
  */
-export function valueObjectCompare(range: BaseValueObject, criteria: BaseValueObject, operator?: compareToken) {
+export function valueObjectCompare(range: BaseValueObject, criteria: BaseValueObject, operator?: compareToken, isCaseSensitive?: boolean) {
```
Comment (wzhudev) [inline packages/engine-formula/src/engine/utils/object-compare.ts:50]: cc @VicKun4937 公式的比较也会复用比较模块吗
