### PR TITLE
fix(sheet): fix toolbar state when there is overlapping selection

### LINKED ISSUE #1515: [Bug]重叠选区合并单元格问题
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现链接

1、选择2个选区，如截图，然后合并单元格
image

### 预期行为

对齐excel或google

### 实际行为

[2024_3_8 11_17_31 commands.json](https://github.com/dream-num/univer/files/14532788/2024_3_8.11_17_31.commands.json)
[2024_3_8 11_17_31 video.webm](https://github.com/dream-num/univer/assets/154207126/186f1e86-2a1c-4c5a-9ee4-e5e848368d55)

### 运行环境

_No response_

### 系统信息

_No response_

### PR DESCRIPTION
**Pull request by ybzky**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #1515 

选区有重合时 不应该允许合并单元格操作 工具栏置灰 （对其excel和google）
#1515

### CODE REVIEW

File: packages/sheets-ui/src/controllers/utils/selections-tools.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import type { IRange } from '@univerjs/core';
+import { SelectionManagerService } from '@univerjs/sheets';
+import type { IAccessor } from '@wendellhu/redi';
+import { Observable } from 'rxjs';
+
+export function rangesIsOverLapping(range1: IRange, range2: IRange): boolean {
```
Comment (wzhudev) [inline packages/sheets-ui/src/controllers/utils/selections-tools.ts:22]: Unit tests are required for basic functions like this. And please move the method to `packages/core/src/shared/rectangle.ts`.

File: packages/sheets-ui/src/controllers/menu/merge.menu.ts [hunk 2]
```diff
@@ -39,7 +48,7 @@ export function CellMergeMenuItemFactory(accessor: IAccessor): IMenuSelectorItem
         type: MenuItemType.SUBITEMS,
         // selections: [...MERGE_CHILDREN],
         hidden$: getMenuHiddenObservable(accessor, UniverInstanceType.SHEET),
-        disabled$,
+        disabled$: disableByPermissionAndSelections$,
```
Comment (wzhudev) [inline packages/sheets-ui/src/controllers/menu/merge.menu.ts:51]: You don't need to manually call `next` on `disableByPermissionAndSelections$`.

```suggestion
        disabled$: disabled$.pipe(
        	combineLatestWith(selectionsHasCross$),
        	map(([disable, hasCross]) => disable || hasCross)
    	)
```

is sufficient.

File: packages/sheets-ui/src/controllers/utils/selections-tools.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+    const rowsOverlap = !(range1.endRow < range2.startRow || range1.startRow > range2.endRow);
+    const columnsOverlap = !(range1.endColumn < range2.startColumn || range1.startColumn > range2.endColumn);
+    return rowsOverlap && columnsOverlap;
+}
+
+export function getSheetSelectionsDisabled$(accessor: IAccessor) {
+    return new Observable<boolean>((subscriber) => {
```
Comment (wzhudev) [inline packages/sheets-ui/src/controllers/utils/selections-tools.ts:29]:
```suggestion
    const selectionManagerService = accessor.get(SelectionManagerService);
    return selectionManagerService.selectionMoveEnd$.pipe(map(/* logic here */), filter(v => typeof v === 'boolean'))
```

Try this to avoid creating `Observable`.

**Review by wzhudev — APPROVED** [review]
Overall looks good. Some code quality issues need to be addressed.
