### PR TITLE
fix(sheet): #1095 the FX content is not cleared after the selected co…

### LINKED ISSUE #1095: [Bug] 选中列删删除列后fx内容未被清空
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、选中列，列第一行有内容，然后删除列

### 预期行为

删除列fx内清空

### 实际行为

[2024_1_11 10_52_02 commands.json](https://github.com/dream-num/univer/files/13896762/2024_1_11.10_52_02.commands.json)
[2024_1_11 10_52_02 video.webm](https://github.com/dream-num/univer/assets/154207126/4f7a6fd9-05e2-4d39-9257-a570bbd7dc8c)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by Gggpound**
…lumn is deleted

- [ ] I am sure that the code is update-to-date with the `dev` branch.

close #1095

### CODE REVIEW

File: packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts [hunk 1]
```diff
@@ -105,6 +121,34 @@ export class FormulaEditorController extends RxDisposable {
         });
     }
 
+    private _syncSelections() {
```
Comment (Jocs) [inline packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts:124]: 建议在 RemoveColCommand.id,RemoveRowCommand.id,InsertRangeMoveRightCommand.id,InsertRangeMoveDownCommand.id, 等 Command 中单独设置 Seleciton，这样 cell editor 监听到 Selection 设置会自动更新内容

**Review by Jocs — CHANGES_REQUESTED** [review]

File: packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts (hunk 1 above)
Comment (Gggpound) [reply packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts]: done

**Review by Jocs — APPROVED** [review]
