### PR TITLE
fix(sheets): boolean should store as number

### LINKED ISSUE #1534: [Feature] TRUE FALSE stored as number 0 1
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

TRUE FALSE stored as string
```js
{
  "v": "FALSE", // FALSE
}
```

### Solution

TRUE FALSE stored as boolean number,like
```js
{
  "v": 0, // FALSE
  "t": CellValueType.BOOLEAN
}
```
Be consistent with Excel

### PR DESCRIPTION
**Pull request by wzhudev**
close #1534

BREAKING CHANGE:
Before:
Boolean values ("TRUE" "FALSE") were stored in the IWorkbooData as strings.
After:
Boolean values would be store as number (0, 1).

- [ ] I am sure that the code is update-to-date with the `dev` branch.

### CODE REVIEW

**Comment by wzhudev** [comment]
@zhaolixin7 Please verify that Boolean values (`TRUE` `FALSE`) work as they used to do.

File: packages/engine-render/src/components/sheets/sheet-skeleton.ts [hunk 1]
```diff
@@ -57,6 +57,7 @@ import {
 
 import { Inject } from '@wendellhu/redi';
 import { distinctUntilChanged, startWith } from 'rxjs';
+import { extractPureTextFromCell } from '@univerjs/core/sheets/worksheet.js';
```
Comment (Dushusir) [inline packages/engine-render/src/components/sheets/sheet-skeleton.ts:60]: 导出到 index.ts再引入

**Review by Dushusir — APPROVED** [review]

**Review by DR-Univer — APPROVED** [review]

**Comment by zhaolixin7** [comment]
@wzhudev 看下这个issue 是这个pr导致的吗？我先assignees你了https://github.com/dream-num/univer/issues/1637
