### PR TITLE
fix: fix text border issue in editor and optimized the active color in panels related to cell color properties

### LINKED ISSUE #5916: [Bug] 单元格设置了边框后输入文字也带边框
### 在您提交此问题之前，您是否检查了以下内容？

- [x] 这真的是个问题吗？
- [x] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

https://stackblitz.com/edit/univer-sheets-vite-8utima2e?file=src%2Fmain.ts,package.json

### 复现链接

复现链接中，B3、B4设置了边框样式后输入的文字也带边框

### 预期行为

输入内容不要边框

### 实际行为

输入内容每个字符都有边框

### 运行环境

_No response_

### 系统信息

_No response_

### PR DESCRIPTION
**Pull request by wpxp123456**
close #5916

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

File: packages/core/src/sheets/util.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export function getFontFormat(format?: Nullable<IStyleData>): IStyleBase {
     if (!format) {
         return {};
     }
-    const { ff, fs, it, bl, ul, st, ol, cl, bg, bd } = format;
+    const { ff, fs, it, bl, ul, st, ol, cl, bg } = format;
     const style: IStyleBase = {};
     ff && (style.ff = ff);
     fs && (style.fs = fs);
```
Comment (VicKun4937) [inline packages/core/src/sheets/util.ts:174]: fs type is boolean number, maybe value is 0, use underfined instead
