### PR TITLE
fix(formula): insert function bug

### LINKED ISSUE #912: [Bug] 公式计算非数值参与计算，编辑态删除公式单元格未清空
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、选择非数值列的单元格添加公式
2、进入编辑删除公式值

### 预期行为

1、对其excel
2、单元格被清空

### 实际行为

[2023_12_27 17_46_55 commands.json](https://github.com/dream-num/univer/files/13777457/2023_12_27.17_46_55.commands.json)
[2023_12_27 17_46_55 video.webm](https://github.com/dream-num/univer/assets/154207126/e5238924-3476-4a04-9394-7bbdb4b91d87)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by Dushusir**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #912

- [x] Whether or not there is a matching refRange, single range with one cell or multiple rows and columns, enter edit mode
- [x] add some test

### CODE REVIEW

File: packages/sheets-formula/src/commands/operations/insert-function.operation.ts [hunk 1]
```diff
@@ -214,6 +235,27 @@ function findStartColumn(cellMatrix: ObjectMatrix<Nullable<ICellData>>, row: num
...
 }
 
-function isNumberCell(cell: Nullable<ICellData>) {
-    return cell && (Tools.isStringNumber(cell.v) || getCellValueType(cell) === CellValueType.NUMBER);
+export function isNumberCell(cell: Nullable<ICellData>) {
+    return (
+        cell &&
+        (cell.t === CellValueType.NUMBER ||
+            getCellValueType(cell) === CellValueType.NUMBER ||
+            Tools.isStringNumber(cell.v))
```
Comment (DR-Univer) [inline packages/sheets-formula/src/commands/operations/insert-function.operation.ts:243]: 这里手动判断单元格类型了，excel也是这样？疑似数字的都统计成数字

**Review by DR-Univer — APPROVED** [review]
