### PR TITLE
fix(sheet): auto-fill conflict with freeze

### LINKED ISSUE #997: [Bug] 选择冻结行上方的单元格下拉填充，无法使用下拉填充
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

image
行显示不连续时，选中截图中单元格，下拉拖拽

### 预期行为

1、选中单元格右下角显示十字光标，可以使用下拉填充
2、下拉填充时拖拽可以连续显示选区，对比excel

### 实际行为

1、选中单元格右下角不显示十字光标
2、需要拖拽到冻结线下方的行数才会显示连续的选区
[2024_1_4 20_08_30 commands.json](https://github.com/dream-num/univer/files/13829643/2024_1_4.20_08_30.commands.json)
[2024_1_4 20_08_30 video.webm](https://github.com/dream-num/univer/assets/154207126/69119e9d-93c6-4f67-afc5-16b9a5794324)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by weird94**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #997

### CODE REVIEW

**Comment by wzhudev** [comment]
@yuhongz Please take a look at this.

File: packages/sheets-ui/src/services/selection/selection-shape-extension.ts [hunk 1]
```diff
@@ -762,6 +814,45 @@ export class SelectionShapeExtension {
 
             scene.setCursor(CURSOR_TYPE.CROSSHAIR);
 
+            const newSelection = this._targetSelection;
+
+            if (viewportMain && currentViewport && this._activeViewport?.viewPortKey !== currentViewport?.viewPortKey) {
```
Comment (DR-Univer) [inline packages/sheets-ui/src/services/selection/selection-shape-extension.ts:819]: 这里应该和之前selection-render.service.ts 里的内容做到外部去。

**Review by DR-Univer — APPROVED** [review]
