### PR TITLE
fix(ui): fix generate facade should execute before hook

### LINKED ISSUE #4682: [Bug] generateHTML method got some error
### Before you submit this issue, have you checked the following

- [x] Is this really a problem?
- [x] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.6.0

### Reproduction link

Image

Image

### Expected behavior

Getting the range's html.

### Actual behavior

Nothing happended, except the error message.

### System information

_No response_

### PR DESCRIPTION
**Pull request by ybzky**
close #4682

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

File: packages/sheets-ui/src/facade/f-range.ts [hunk 1]
```diff
@@ -179,11 +179,19 @@ class FRangeSheetsUIMixin extends FRange implements IFRangeSheetsUIMixin {
...
 
     override generateHTML(): string {
-        const copyContent = this._injector.get(ISheetClipboardService).generateCopyContent(
+        const clipboardService = this._injector.get(ISheetClipboardService);
+        const hooks = clipboardService.getClipboardHooks();
+        const unitId = this._workbook.getUnitId();
+        const subUnitId = this._worksheet.getSheetId();
+        const range = this._range;
+
+        hooks.forEach((h) => h.onBeforeCopy?.(unitId, subUnitId, range, COPY_TYPE.COPY));
```
Comment (wzhudev) [inline packages/sheets-ui/src/facade/f-range.ts:188]: We should not expose implementation details in the Facade layer, maybe there should be a `generateCopyContent` method in the clipboard service to invoke the hooks and do other things.

**Review by wzhudev — APPROVED** [review]
LGTM
