### PR TITLE
fix: fx editor cursor

### LINKED ISSUE #810: [Bug]编辑态时展开fx栏，光标错位，单元格错位
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

进入编辑态，点击fx栏向下展开按钮

### 预期行为

光标位置单元格中显示

### 实际行为

image
image

### 运行环境

其他 (请在复现步骤中说明)

### 操作系统

Windows

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by Jocs**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #810

### CODE REVIEW

**Review by jikkai — APPROVED** [review]
LGTM

File: packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts [hunk 1]
```diff
@@ -157,6 +158,12 @@ export class FormulaEditorController extends RxDisposable {
         });
     }
 
+    private _listenFoldBtnClick() {
+        this._formulaEditorManagerService.foldBtnStatus$.pipe(takeUntil(this.dispose$)).subscribe(() => {
```
Comment (wzhudev) [inline packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts:162]: What if there are other events that may change the workbench's layout? An abstraction of this type of events would be better.
