### PR TITLE
fix: refresh cell size after edit by zen editor

### LINKED ISSUE #931: [Bug] 退出禅模式时编辑，编辑框与单元格大小不一致
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、进入禅模式输入换行内容
2、退出禅模式
3、输入内容

### 预期行为

显示的编辑框与选中的单元格大小一致

### 实际行为

[2024_1_5 15_25_07 commands.json](https://github.com/dream-num/univer/files/13839241/2024_1_5.15_25_07.commands.json)
[2024_1_5 15_25_07 video.webm](https://github.com/dream-num/univer/assets/154207126/af4392c2-79f8-4c26-b191-48004b4312eb)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by Jocs**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #931

### CODE REVIEW

File: packages/sheets-ui/src/controllers/editor-bridge.controller.ts [hunk 1]
```diff
@@ -77,7 +77,12 @@ export class EditorBridgeController extends RxDisposable {
     }
 
     private _initSelectionChangeListener() {
-        merge(this._selectionManagerService.selectionMoveEnd$, this._selectionManagerService.selectionMoveStart$)
+        merge(
+            this._selectionManagerService.selectionMoveEnd$,
+            this._selectionManagerService.selectionMoveStart$,
+            // The cell size will change after edit by zen-editor, so need to refresh state(endY AND endX).
+            this._editorBridgeService.refreshState$
```
Comment (DR-Univer) [inline packages/sheets-ui/src/controllers/editor-bridge.controller.ts:84]: zen模式是根据这个state的变化启动的？

**Review by DR-Univer — APPROVED** [review]
