### PR TITLE
fix(sheet): freeze select selection issues

### LINKED ISSUE #939: [Bug] 有冻结行列时，无法向下选择选区
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、有冻结行，选择冻结行上方单元格向下选择选区或下拉填充

### 预期行为

对齐excelimage

### 实际行为

[2023_12_29 15_55_32 commands.json](https://github.com/dream-num/univer/files/13791825/2023_12_29.15_55_32.commands.json)
[2023_12_29 15_55_32 video.webm](https://github.com/dream-num/univer/assets/154207126/ea7816d7-454f-4da1-9118-0b53a8ef5336)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### LINKED ISSUE #941: [Bug] 冻结区域内隐藏行列，隐藏后冻结位置不对
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

dev

### 复现步骤

1、冻结到C列，然后隐藏B列

### 预期行为

image

### 实际行为

[2023_12_29 16_48_42 commands.json](https://github.com/dream-num/univer/files/13792121/2023_12_29.16_48_42.commands.json)
[2023_12_29 16_48_42 video.webm](https://github.com/dream-num/univer/assets/154207126/ba5514de-a8fc-4dad-93e1-502825178a3a)

### 运行环境

_No response_

### 操作系统

_No response_

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by weird94**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #939
close #941

### CODE REVIEW

File: packages/engine-render/src/scroll-timer.ts [hunk 1]
```diff
@@ -16,9 +16,11 @@
 
 import type { IPaddingData, Nullable } from '@univerjs/core';
 
+import type { Scene, Viewport } from '.';
```
Comment (wzhudev) [inline packages/engine-render/src/scroll-timer.ts:19]: Be careful about the import path

Comment (weird94) [reply packages/engine-render/src/scroll-timer.ts]: fixed

**Review by wzhudev — APPROVED** [review]
