### PR TITLE
fix: move range cause border wrong style

### LINKED ISSUE #766: [Bug]边框- 移动选区时边框丢失
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

最新

### 复现步骤

https://github.com/dream-num/univer/assets/145178365/7f1900f6-d9f6-4d86-96ba-ad4316bd14f5

### 预期行为

复现Google sheet 的表现

### 实际行为

未复现

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by weird94**
- [x] I am sure that the code is update-to-date with the `dev` branch.

close #766

### CODE REVIEW

File: packages/engine-render/src/components/sheets/extensions/border.ts [hunk 1]
```diff
@@ -110,6 +110,32 @@ export class Border extends SheetExtension {
                         preColor = color;
                     }
 
+                    // make sure border would not overlap
+                    switch (type) {
```
Comment (DR-Univer) [inline packages/engine-render/src/components/sheets/extensions/border.ts:114]: 可以的，还考虑到了多余的渲染开销！！牛

**Review by DR-Univer — APPROVED** [review]
