### PR TITLE
fix: sheet menu item

### LINKED ISSUE #448: [Bug] sheet.command.set-worksheet-col-width menu item not show when select multi column
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

@univerjs/ui-plugin-sheets

### 复现步骤

1. 选择多行 或者 多列。 select multi row or multi column
2. 点击鼠标右键。 click the right button of mouse

### 预期行为

菜单栏应该显示调节 行高 / 列宽 菜单。
menu show set-worksheet-row-height / set-worksheet-col-width item

### 实际行为

菜单栏未显示调节 行高 / 列宽 菜单。
menu didn‘t show set-worksheet-row-height / set-worksheet-col-width item

### 运行环境

Chrome

### 操作系统

macOS

### 构建工具

_No response_

### PR DESCRIPTION
**Pull request by weird94**
close #448

### CODE REVIEW

File: packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts [hunk 1]
```diff
@@ -58,7 +69,15 @@ export class SheetContextMenuController extends Disposable {
         const spreadsheetPointerDownObserver = objects.spreadsheet.onPointerDownObserver;
         const spreadsheetObserver = spreadsheetPointerDownObserver.add((event) => {
             if (event.button === 2) {
-                this._contextMenuService.triggerContextMenu(event, MenuPosition.CONTEXT_MENU);
+                const selections = this._selectionManagerService.getSelections();
```
Comment (wzhudev) [inline packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts:72]: The commented code above should be removed.

File: packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts [hunk 2]
```diff
@@ -58,7 +69,15 @@ export class SheetContextMenuController extends Disposable {
...
+                const rangeType = selections?.length ? selections[0].range.rangeType : undefined;
+                if (rangeType === RANGE_TYPE.COLUMN) {
+                    this._contextMenuService.triggerContextMenu(event, SheetMenuPosition.COL_HEADER_CONTEXT_MENU);
```
Comment (wzhudev) [inline packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts:75]: Could extract a function because there are similar pieces of code.

```ts
const triggerMenu = (position: SheetMenuPosition) => {
  this._contextMenuService.triggerContextMenu(event, position);
}
```

**Review by wzhudev — CHANGES_REQUESTED** [review]
Some code quality issues need to be addressed.

**Comment by jikkai** [comment]
`MenuPosition` and `SheetMenuPosition` are actually the same thing, I will fix it in the next PR :godmode:

File: packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts (hunk 1 above)
Comment (weird94) [reply packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts:72]: history code, i will remove it.

**Review by wzhudev — APPROVED** [review]
LGTM! Welcome to Univer!
