### PR TITLE
fix: fix formula calculation for empty strings

### LINKED ISSUE #4867: [Bug] Divergent Error Handling in Excel vs Univer: Blank Cell Multiplication Scenarios Lead to Inconsistent Conditional Logic Results
### Before you submit this issue, have you checked the following

- [x] Is this really a problem?
- [x] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.6.6

### Reproduction link

[【BUG】单元格由公式计算输出结果为空 ≠ 空白单元格.xlsx](https://github.com/user-attachments/files/19386482/BUG.xlsx)
The formula in cell D4, IFERROR(B4\*C4, ""), outputs an empty string when an error occurs. When cell E4 references column D for calculation, the result of B4\*D4 is incorrect. Normally, multiplying a number with a blank cell should not output 0, but Univer does not distinguish between these scenarios—B4*D4 still returns 0. Consequently, when performing conditional logic judgments based on such scenarios, the results differ entirely from Excel's behavior.

Image

### Expected behavior

#VALUE!

### Actual behavior

0

### System information

 System:
    OS: macOS 15.3.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 72.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 10.5.2 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
    bun: 0.6.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 134.0.6998.118
    Safari: 18.3.1

### PR DESCRIPTION
**Pull request by wpxp123456**
close #4867

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

File: packages/engine-formula/src/engine/utils/cell.ts [hunk 1]
```diff
@@ -35,5 +35,5 @@ export function getCellValue(cell: Nullable<ICellData>) {
         return newDataStream;
     }
 
-    return cell?.v || 0;
+    return cell?.v ?? 0;
```
Comment (VicKun4937) [inline packages/engine-formula/src/engine/utils/cell.ts:38]: when the v is empty string, in left code , it will return 0 by || 0 , in the right one , it will return ''

Comment (VicKun4937) [reply packages/engine-formula/src/engine/utils/cell.ts:38]: please confirm above case

File: packages/engine-formula/src/engine/utils/cell.ts [hunk 2]
```diff
@@ -14,8 +14,8 @@
  * limitations under the License.
  */
 
-import { BuildTextUtils } from '@univerjs/core';
 import type { ICellData, Nullable } from '@univerjs/core';
+import { BuildTextUtils } from '@univerjs/core';
 
 export function getCellValue(cell: Nullable<ICellData>) {
     if (cell === null) {
```
Comment (VicKun4937) [inline packages/engine-formula/src/engine/utils/cell.ts:21]: is the cell may be undefined

**Review by VicKun4937 — APPROVED** [review]
