### PR TITLE
fix: merged cell bg not fully ender

### LINKED ISSUE #3704: [Bug] Off-screen merged column cell styles do not take effect
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

v0.3.0

### Reproduction link

https://univer.ai/zh-CN/examples/sheets

### Expected behavior

Off-screen merged column cell styles take effect

### Actual behavior

When a merged column is out of the screen range, set the style for this merged cell, and then when you scroll the horizontal scroll bar, the off-screen style will not take effect.

### System information

_No response_

### PR DESCRIPTION
**Pull request by lumixraku**
close https://github.com/dream-num/univer-pro/issues/2716
close #3704

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Comment by oumomomo** [comment]
CRTL+A选中所有单元格设置背景色，再合并表格内所有单元格不展示背景色
[2024_10_9 20_44_20 video.webm](https://github.com/user-attachments/assets/94400cb5-6be4-4ea5-87aa-fd4c1f00259e)

File: packages/engine-render/src/components/sheets/extensions/font.ts [hunk 1]
```diff
@@ -103,11 +104,36 @@ export class Font extends SheetExtension {
...
             range.endColumn += EXPAND_SIZE_FOR_RENDER_OVERFLOW;
             range = clampRange(range);
             Range.foreach(range, (row, col) => {
+                const cellInfo = spreadsheetSkeleton.getCellByIndexWithNoHeader(row, col);
+                if (!cellInfo) return;
+
+                // put all merged cell to another pass to handle.
+                if (cellInfo.isMerged || cellInfo.isMergedMainCell) {
+                    // to check if mergeRanges has this merge range already. if not, push it.
+                    const f = mergeRanges.filter((r: IRange) => {
```
Comment (VicKun4937) [inline packages/engine-render/src/components/sheets/extensions/font.ts:120]: should we make sure this part time complex is O(1), O(N) maybe cause  performance issue

**Review by VicKun4937 — APPROVED** [review]
LGTM
