### PR TITLE
fix(formula): fix some bug

### LINKED ISSUE #3772: [Bug] formula if issue
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.3.0

### Reproduction link

I don't know how to use the online template, so I provide the workbook data.

```json
{
    "id": "XGBQ9r",
    "sheetOrder": ["esfePQ9lBZ68_24tVAVzo"],
    "name": "",
    "appVersion": "0.3.0",
    "locale": "zhCN",
    "styles": {
        "2rWMxl": {"bg": {"rgb": "#EFFBD0"}},
        "0B_XQP": {
            "ff": "Arial",
            "fs": 11,
            "it": 0,
            "bl": 0,
            "ul": {"s": 0},
            "st": {"s": 0},
            "ol": {"s": 0},
            "tr": {"a": 0, "v": 0},
            "td": 0,
            "bg": {"rgb": "#EFFBD0"},
            "ht": 0,
            "vt": 0,
            "tb": 0,
            "pd": {"t": 0, "b": 2, "l": 2, "r": 2},
            "cl": null,
            "n": null
        },
        "xNReZo": {
            "ff": "Arial",
            "fs": 11,
            "it": 0,
            "bl": 0,
            "ul": {"s": 0},
            "st": {"s": 0},
            "ol": {"s": 0},
            "tr": {"a": 0, "v": 0},
            "td": 0,
            "ht": 0,
            "vt": 0,
            "tb": 0,
            "pd": {"t": 0, "b": 2, "l": 2, "r": 2},
            "cl": null,
            "bg": null,
            "n": null
        }
    },
    "sheets": {
        "esfePQ9lBZ68_24tVAVzo": {
            "id": "esfePQ9lBZ68_24tVAVzo",
            "name": "Sheet1",
            "tabColor": "",
            "hidden": 0,
            "rowCount": 1000,
            "columnCount": 20,
            "zoomRatio": 1,
            "freeze": {"xSplit": 0, "ySplit": 0, "startRow": -1, "startColumn": -1},
            "scrollTop": 0,
            "scrollLeft": 0,
            "defaultColumnWidth": 88,
            "defaultRowHeight": 24,
            "mergeData": [],
            "cellData": {
                "6": {"2": {"v": "异常", "t": 1}, "4": {"v": "正常", "t": 1}},
                "7": {"2": {"s": "2rWMxl", "v": 1, "t": 2}, "4": {"v": 1, "t": 2, "s": "0B_XQP"}},
                "8": {"4": {"s": "xNReZo"}},
                "9": {"4": {"s": "xNReZo"}},
                "10": {"4": {"s": "xNReZo"}},
                "11": {"4": {"s": "xNReZo"}},
                "12": {"4": {"s": "xNReZo"}},
                "13": {"4": {"s": "xNReZo"}},
                "14": {"4": {"s": "xNReZo"}},
                "15": {"4": {"s": "xNReZo"}},
                "16": {"4": {"s": "xNReZo"}},
                "17": {"4": {"s": "xNReZo"}},
                "18": {"4": {"s": "xNReZo"}},
                "19": {"4": {"s": "xNReZo"}},
                "20": {"4": {"s": "xNReZo"}},
                "21": {"4": {"s": "xNReZo"}},
                "22": {"4": {"s": "xNReZo"}},
                "23": {"4": {"s": "xNReZo"}},
                "24": {"4": {"s": "xNReZo"}},
                "25": {"4": {"s": "xNReZo"}},
                "26": {"4": {"s": "xNReZo"}},
                "27": {"4": {"s": "xNReZo"}},
                "28": {"4": {"s": "xNReZo"}},
                "29": {
                    "2": {"f": "=IF(C8<0,IF(C31<1,1,0.8),IF(C31<1,0.95,1))", "v": 1, "t": 2},
                    "4": {
                        "s": "xNReZo",
                        "f": "=IF(E8<0,IF(E31<1,1,0.8),IF(E31<1,0.95,1))",
                        "si": "EDVgVn",
                        "v": 0.95,
                        "t": 2
                    }
                },
                "30": {"2": {"f": "=C32/100", "v": 0.01, "t": 2}, "4": {"s": "0B_XQP", "v": 0.01, "t": 2}},
                "31": {"2": {"s": "2rWMxl", "v": 1, "t": 2}, "4": {"s": "xNReZo"}}
            },
            "rowData": {
                "6": {"hd": 0, "h": 24, "ah": 24},
                "7": {"hd": 0, "h": 24, "ah": 24},
                "8": {"hd": 0, "h": 24},
                "9": {"hd": 0, "h": 24},
                "10": {"hd": 0, "h": 24},
                "11": {"hd": 0, "h": 24},
                "12": {"hd": 0, "h": 24},
                "13": {"hd": 0, "h": 24},
                "14": {"hd": 0, "h": 24},
                "15": {"hd": 0, "h": 24},
                "16": {"hd": 0, "h": 24},
                "17": {"hd": 0, "h": 24},
                "18": {"hd": 0, "h": 24},
                "19": {"hd": 0, "h": 24},
                "20": {"hd": 0, "h": 24},
                "21": {"hd": 0, "h": 24},
                "22": {"hd": 0, "h": 24},
                "23": {"hd": 0, "h": 24},
                "24": {"hd": 0, "h": 24},
                "25": {"hd": 0, "h": 24},
                "26": {"hd": 0, "h": 24},
                "27": {"hd": 0, "h": 24},
                "28": {"hd": 0, "h": 24},
                "29": {"hd": 0, "h": 24, "ah": 24},
                "30": {"hd": 0, "h": 24, "ah": 24},
                "31": {"hd": 0, "h": 24, "ah": 24}
            },
            "columnData": {"2": {"w": 88, "hd": 0}, "4": {"w": 88, "hd": 0}, "5": {"w": 88, "hd": 0}},
            "showGridlines": 1,
            "rowHeader": {"width": 46, "hidden": 0},
            "columnHeader": {"height": 20, "hidden": 0},
            "rightToLeft": 0
        }
    },
    "resources": [{"name": "SHEET_RANGE_PROTECTION_PLUGIN", "data": "{}"}, {
        "name": "SHEET_WORKSHEET_PROTECTION_PLUGIN",
        "data": "{}"
    }, {"name": "SHEET_WORKSHEET_PROTECTION_POINT_PLUGIN", "data": "{}"}, {
        "name": "SHEET_DEFINED_NAME_PLUGIN",
        "data": "{}"
    }, {"name": "SHEET_DATA_VALIDATION_PLUGIN", "data": "{}"}, {
        "name": "SHEET_AuthzIoMockService_PLUGIN",
        "data": "{}"
    }]
}
```

### Expected behavior

formula if(..., if(...), if(...)) can work without any issue.

### Actual behavior

try to reset the C8 using value "1"， we can get the correct result such as "the value of C30 is 0.95";
try to reset the C32 using value "1", we can get the incorrect result such as "the value of C30 is 1";

and on the other hand, 
try to reset  the E8 using value "1", or reset the E31 using value 0.01, we can always get the correct result such as "the value of E30 is 0.95".

formula-if-issue

### System information

_No response_

### PR DESCRIPTION
**Pull request by wpxp123456**
close #3772 
close https://github.com/dream-num/univer-pro/issues/2894
close https://github.com/dream-num/univer-pro/issues/2440
close https://github.com/dream-num/univer-pro/issues/2212

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

File: packages/sheets-formula-ui/src/controllers/utils/utils.ts [hunk 1]
```diff
@@ -32,9 +32,13 @@ export function whenEditorStandalone(contextService: IContextService) {
  * @param cell
  * @returns
  */
-export function extractFormulaError(cell: Nullable<ICellData>) {
+export function extractFormulaError(cell: Nullable<ICellData>, isArrayFormulaCell: boolean = false) {
```
Comment (Dushusir) [inline packages/sheets-formula-ui/src/controllers/utils/utils.ts:35]: Why is it duplicated with the extractFormulaError method in sheets-formula?

**Review by Dushusir — APPROVED** [review]

File: packages/sheets-formula-ui/src/controllers/utils/utils.ts (hunk 1 above)
Comment (Dushusir) [reply packages/sheets-formula-ui/src/controllers/utils/utils.ts:35]: Subsequent optimization
