### PR TITLE
fix(thread-comment): fix thread comment root editor id

### LINKED ISSUE #6026: [Bug] Find&Replace icon disabled after adding a comment
### Before you submit this issue, have you checked the following

- [x] Is this really a problem?
- [x] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.10.12

## See Video

https://github.com/user-attachments/assets/72d6d9c5-bc7b-46c5-b92d-d8893bf43ace

### Expected behavior

Add comment -> **Click on comment input** -> Find&Replace icon is disabled and can't be restored

### Actual behavior

Add comment -> **Click on comment input** -> Find&Replace icon is disabled and can't be restored

### System information

_No response_

### PR DESCRIPTION
**Pull request by wpxp123456**
close #6026

## Pull Request Checklist

- [ ] Related tickets or issues have been linked in the PR description (or missing issue).
- [ ] [Naming convention](https://github.com/dream-num/univer/blob/dev/docs/NAMING_CONVENTION.md) is followed (**do please** check it especially when you created new plugins, commands and resources).
- [ ] Unit tests have been added for the changes (if applicable).
- [ ] Breaking changes have been documented (or no breaking changes introduced in this PR).

### CODE REVIEW

**Review by jikkai — APPROVED** [review]

File: packages/thread-comment-ui/src/views/thread-comment-editor/index.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export const ThreadCommentEditor = forwardRef<IThreadCommentEditorInstance, IThr
     const [editing, setEditing] = useState(false);
     const editorService = useDependency(IEditorService);
     const editor = useRef<Editor>(null);
-    const rootEditorId = type === UniverInstanceType.UNIVER_SHEET ? DOCS_NORMAL_EDITOR_UNIT_ID_KEY : unitId;
+    const rootEditorId = type === UniverInstanceType.UNIVER_DOC ? DOCS_NORMAL_EDITOR_UNIT_ID_KEY : unitId;
```
Comment (jikkai) [inline packages/thread-comment-ui/src/views/thread-comment-editor/index.tsx]: lol
